sudo: required
dist: trusty

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - PHPUNIT=3.7.33

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.5
      env:
        - LINTR=1
          LINTR_COMMENT_BOT=false
  include:
    - php: 5.5
      env:
        - COVERALLS=1

    - php: 5.5
      env:
        - LINTR=1
          LINTR_COMMENT_BOT=false

    - php: 7.0
      env:
        - PHPCS=1

    - php: 7.1
      env:
        - PHPUNIT=5.7.19

    - php: 7.2
      env:
        - PHPUNIT=5.7.19

cache:
  directories:
    - $HOME/R/Library

before_script:
  - sudo apt-get install -y --force-yes r-base r-cran-rserve
  - sudo apt-get install -y --force-yes libcurl4-gnutls-dev
  - sudo apt-get install -y --force-yes libxml2-dev
  - sudo mkdir -p ~/R/Library
  - sudo echo 'R_LIBS=~/R/Library' > ~/.Renviron
  - sudo echo 'options(repos = "https://cran.rstudio.com")' > ~/.Rprofile
  - sudo Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
  - sudo Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
  - sudo Rscript -e 'if(!"gplots" %in% rownames(installed.packages())) { install.packages("gplots", dependencies = TRUE) }'
  - sudo Rscript -e 'if(!"ggplot2" %in% rownames(installed.packages())) { install.packages("ggplot2", dependencies = TRUE) }'
  - sudo Rscript -e 'if(!"gridExtra" %in% rownames(installed.packages())) { install.packages("gridExtra", dependencies = TRUE) }'
  - sudo Rscript -e 'if(!"psy" %in% rownames(installed.packages())) { install.packages("psy", dependencies = TRUE) }'
  - sudo Rscript -e 'update.packages(ask = FALSE, instlib = "~/R/Library")'
  - sudo sh -c "rm /usr/lib/R/bin/Rserve"
  - sudo sh -c "rm /usr/lib/R/bin/Rserve.dbg"
  - sudo sh -c "ln -s /usr/lib/R/site-library/Rserve/libs/Rserve /usr/lib/R/bin/Rserve"
  - sudo sh -c "ln -s /usr/lib/R/site-library/Rserve/libs/Rserve.dbg /usr/lib/R/bin/Rserve.dbg"
  - sudo R CMD Rserve
  - sh -c "mysql -e 'CREATE DATABASE qdnatool_test;'"
  - chmod -R 777 ./app/tmp
  - composer require "phpunit/phpunit=$PHPUNIT"
  - sh -c "if [ '$PHPCS' = '1' ]; then app/Vendor/bin/phpcs --config-set installed_paths app/Vendor/cakephp/cakephp-codesniffer; fi"
  - phpenv rehash
  - echo -e "<?php\nclass DATABASE_CONFIG {\n\n\tpublic \$test = array(\n\t\t'datasource' => 'Database/Mysql',\n\t\t'database' => 'qdnatool_test',\n\t\t'host' => '0.0.0.0',\n\t\t'login' => 'travis',\n\t\t'persistent' => false,\n\t);\n}" > app/Config/database.php
  - echo -e "<?php\n\$config = array(\n\t'Rserve' => array(\n\t\t'host' => 'localhost',\n\t\t'port' => 6311,\n\t\t'debug' => false\n\t)\n);\n" > app/Config/rserve.php

script:
  - sh -c "if [ '$COVERALLS' = 1 ]; then cd ./app; Vendor/bin/cake test app All --stderr --coverage-clover ../build/logs/clover.xml --configuration ../phpunit.xml; cd ..; fi;"
  - sh -c "if [ '$PHPCS' = '1' ]; then app/Vendor/bin/phpcs -p --extensions=php --standard=CakePHP --ignore=Plugin --ignore=Vendor --ignore=webroot/js/ckeditor -n ./app; fi;"
  - sh -c "if [ '$PHPCS' != '1' ] && [ '$COVERALLS' != 1 ] && [ '$LINTR' != 1 ]; then cd ./app; Vendor/bin/cake test app All --stderr; cd ..; fi"
  - sh -c "if [ '$LINTR' = '1' ]; then ./bin/travis-linter.sh; fi"
after_success:
  - sh -c "if [ '$COVERALLS' = '1' ]; then php app/Vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
