sudo: required
dist: trusty

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - R=3.4
    - R=3.5
  global:
    - PHPUNIT=3.7.33

matrix:
  include:
    - php: 5.5
      env:
        - R=3.0.2

    - php: 5.5
      env:
        - COVERALLS=1

    - php: 5.5
      env:
        - LINTR=1
        - LINTR_COMMENT_BOT=false
        - R=3.5

    - php: 7.0
      env:
        - PHPCS=1

    - php: 7.1
      env:
        - PHPUNIT=5.7.19

    - php: 7.2
      env:
        - PHPUNIT=5.7.19

    - php: 7.3
      env:
        - PHPUNIT=5.7.19

  exclude:
    - php: 7.2
    - php: 7.3

cache:
  directories:
    - $HOME/R/Library
    - $HOME/downloads

before_script:

  - sudo sh -c "if [ '$R' = '3.4' ] || [ '$R' = '3.5' ]; then apt-key adv --keyserver keyserver.ubuntu.com --recv E084DAB9; fi"
  - sudo sh -c "if [ '$R' = '3.4' ]; then add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu trusty/' -y; fi"
  - sudo sh -c "if [ '$R' = '3.5' ]; then add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/' -y; fi"
  - sudo sh -c "if [ '$R' = '3.4' ] || [ '$R' = '3.5' ]; then apt-get update -qq; fi"
  - sudo apt-get install -y --force-yes r-base r-cran-rserve
  - sudo apt-get install -y --force-yes libcurl4-gnutls-dev
  - sudo apt-get install -y --force-yes libxml2-dev
  - sudo mkdir -p ~/R/Library
  - sudo echo 'R_LIBS=~/R/Library' > ~/.Renviron
  - sudo echo 'options(repos = "https://cran.rstudio.com")' > ~/.Rprofile
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/gtools/gtools_3.4.1.tar.gz\" -O \"gtools_3.4.1.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"gtools\" %in% rownames(installed.packages())) { install.packages(\"gtools_3.4.1.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/gdata/gdata_2.13.3.tar.gz\" -O \"gdata_2.13.3.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"gdata\" %in% rownames(installed.packages())) { install.packages(\"gdata_2.13.3.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/bitops_1.0-6.tar.gz\" -O \"bitops_1.0-6.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"bitops\" %in% rownames(installed.packages())) { install.packages(\"bitops_1.0-6.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/caTools/caTools_1.17.tar.gz\" -O \"caTools_1.17.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"caTools\" %in% rownames(installed.packages())) { install.packages(\"caTools_1.17.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/gplots/gplots_2.14.1.tar.gz\" -O \"gplots_2.14.1.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"gplots\" %in% rownames(installed.packages())) { install.packages(\"gplots_2.14.1.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/Rcpp/Rcpp_0.11.2.tar.gz\" -O \"Rcpp_0.11.2.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"Rcpp\" %in% rownames(installed.packages())) { install.packages(\"Rcpp_0.11.2.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/plyr/plyr_1.8.1.tar.gz\" -O \"plyr_1.8.1.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"plyr\" %in% rownames(installed.packages())) { install.packages(\"plyr_1.8.1.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/digest/digest_0.6.4.tar.gz\" -O \"digest_0.6.4.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"digest\" %in% rownames(installed.packages())) { install.packages(\"digest_0.6.4.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/gtable/gtable_0.1.2.tar.gz\" -O \"gtable_0.1.2.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"gtable\" %in% rownames(installed.packages())) { install.packages(\"gtable_0.1.2.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/stringr/stringr_0.6.2.tar.gz\" -O \"stringr_0.6.2.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"stringr\" %in% rownames(installed.packages())) { install.packages(\"stringr_0.6.2.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/reshape2/reshape2_1.4.tar.gz\" -O \"reshape2_1.4.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"reshape2\" %in% rownames(installed.packages())) { install.packages(\"reshape2_1.4.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/RColorBrewer/RColorBrewer_1.0-5.tar.gz\" -O \"RColorBrewer_1.0-5.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"RColorBrewer\" %in% rownames(installed.packages())) { install.packages(\"RColorBrewer_1.0-5.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/dichromat_2.0-0.tar.gz\" -O \"dichromat_2.0-0.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"dichromat\" %in% rownames(installed.packages())) { install.packages(\"dichromat_2.0-0.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/colorspace/colorspace_1.2-4.tar.gz\" -O \"colorspace_1.2-4.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"colorspace\" %in% rownames(installed.packages())) { install.packages(\"colorspace_1.2-4.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/munsell/munsell_0.4.2.tar.gz\" -O \"munsell_0.4.2.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"munsell\" %in% rownames(installed.packages())) { install.packages(\"munsell_0.4.2.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/labeling/labeling_0.2.tar.gz\" -O \"labeling_0.2.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"labeling\" %in% rownames(installed.packages())) { install.packages(\"labeling_0.2.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/scales/scales_0.2.4.tar.gz\" -O \"scales_0.2.4.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"scales\" %in% rownames(installed.packages())) { install.packages(\"scales_0.2.4.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/proto/proto_0.3-10.tar.gz\" -O \"proto_0.3-10.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"proto\" %in% rownames(installed.packages())) { install.packages(\"proto_0.3-10.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/ggplot2/ggplot2_1.0.0.tar.gz\" -O \"ggplot2_1.0.0.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"ggplot2\" %in% rownames(installed.packages())) { install.packages(\"ggplot2_1.0.0.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/Archive/gridExtra/gridExtra_0.9.1.tar.gz\" -O \"gridExtra_0.9.1.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"gridExtra\" %in% rownames(installed.packages())) { install.packages(\"gridExtra_0.9.1.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sh -c "if [ '$R' = '3.0.2' ]; then wget \"https://cran.r-project.org/src/contrib/psy_1.1.tar.gz\" -O \"psy_1.1.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.0.2' ]; then Rscript -e 'if(!\"psy\" %in% rownames(installed.packages())) { install.packages(\"psy_1.1.tar.gz\", repo = NULL, type=\"source\") }'; fi"
  - sudo sh -c "if [ '$R' = '3.4' ]; then Rscript -e 'if(!\"psy\" %in% rownames(installed.packages())) { install.packages(\"psy\", dependencies = TRUE) }'; fi"
  - sudo sh -c "if [ '$R' = '3.4' ]; then Rscript -e 'if(!\"gplots\" %in% rownames(installed.packages())) { install.packages(\"gplots\", dependencies = TRUE) }'; fi"
  - sudo sh -c "if [ '$R' = '3.4' ]; then Rscript -e 'if(!\"ggplot2\" %in% rownames(installed.packages())) { install.packages(\"ggplot2\", dependencies = TRUE) }'; fi"
  - sudo sh -c "if [ '$LINTR' = '1' ]; then Rscript -e 'if(!\"lintr\" %in% rownames(installed.packages())) { install.packages(\"lintr\", dependencies = TRUE) }'; fi"
  - sudo sh -c "rm /usr/lib/R/bin/Rserve"
  - sudo sh -c "rm /usr/lib/R/bin/Rserve.dbg"
  - sudo sh -c "ln -s /usr/lib/R/site-library/Rserve/libs/Rserve /usr/lib/R/bin/Rserve"
  - sudo sh -c "ln -s /usr/lib/R/site-library/Rserve/libs/Rserve.dbg /usr/lib/R/bin/Rserve.dbg"
  - sudo R CMD Rserve
  - sh -c "mysql -e 'CREATE DATABASE qdnatool_test;'"
  - chmod -R 777 ./app/tmp
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require \"satooshi/php-coveralls=v1.0.1\"; fi"
  - sh -c "if [ '$PHPUNIT' != '3.7.33' ]; then composer remove --dev \"phpunit/phpunit\"; fi"
  - composer require "phpunit/phpunit=$PHPUNIT"
  - sh -c "if [ '$PHPCS' = '1' ]; then cd $TRAVIS_BUILD_DIR/app; Vendor/bin/phpcs --config-set installed_paths Vendor/cakephp/cakephp-codesniffer; fi"
  - phpenv rehash
  - echo -e "<?php\nclass DATABASE_CONFIG {\n\n\tpublic \$test = array(\n\t\t'datasource' => 'Database/Mysql',\n\t\t'database' => 'qdnatool_test',\n\t\t'host' => '0.0.0.0',\n\t\t'login' => 'travis',\n\t\t'persistent' => false,\n\t);\n}" > app/Config/database.php
  - echo -e "<?php\n\$config = array(\n\t'Rserve' => array(\n\t\t'host' => 'localhost',\n\t\t'port' => 6311,\n\t\t'debug' => false\n\t)\n);\n" > app/Config/rserve.php

script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then cd $TRAVIS_BUILD_DIR/app; Vendor/bin/cake test app AllTests --stderr --coverage-clover ../build/logs/clover.xml --configuration ../phpunit.xml; fi;"
  - sh -c "if [ '$PHPCS' = '1' ]; then cd $TRAVIS_BUILD_DIR/app; Vendor/bin/phpcs -p --extensions=php --standard=CakePHP --ignore=Plugin --ignore=Vendor --ignore=webroot/js/ckeditor -n $TRAVIS_BUILD_DIR; fi;"
  - sh -c "if [ '$PHPCS' != '1' ] && [ '$COVERALLS' != 1 ] && [ '$LINTR' != 1 ]; then cd $TRAVIS_BUILD_DIR/app; Vendor/bin/cake test app AllTests --stderr; fi"
  - sh -c "if [ '$LINTR' = '1' ]; then cd $TRAVIS_BUILD_DIR; ./bin/travis-linter.sh; fi"
after_success:
  - sh -c "if [ '$COVERALLS' = '1' ]; then cd $TRAVIS_BUILD_DIR; php app/Vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
