sudo: required
dist: xenial

services:
  - mysql

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - R=3.0.2
    - R=3.4
    - R=3.5
  global:
    - PHPUNIT=3.7.33
      R=3.2.3

matrix:

  include:
    - php: 7.0
      env:
        - COVERALLS=1
        - R=3.0.2

    - php: 7.0
      env:
        - LINTR=1
          LINTR_COMMENT_BOT=false

    - php: 7.0
      env:
        - PHPCS=1

    - php: 7.1
      env:
        - PHPUNIT=5.7.19
        - R=3.4

    - php: 7.2
      env:
        - PHPUNIT=5.7.19
        - R=3.0.2

    - php: 7.2
      env:
        - PHPUNIT=5.7.19
        - R=3.4

    - php: 7.2
      env:
        - PHPUNIT=5.7.19
        - R=3.5

    - php: 7.3
      env:
        - PHPUNIT=5.7.19
        - R=3.0.2

    - php: 7.3
      env:
        - PHPUNIT=5.7.19
        - R=3.4

    - php: 7.3
      env:
        - PHPUNIT=5.7.19
        - R=3.5

  exclude:
    - php: 7.2
      env: R=3.0.2
    - php: 7.2
      env: R=3.4
    - php: 7.2
      env: R=3.5
    - php: 7.3
      env: R=3.0.2
    - php: 7.3
      env: R=3.4
    - php: 7.3
      env: R=3.5

cache:
  directories:
    - $HOME/R/Library
    - $HOME/downloads

before_script:

  - sudo sh -c "if [ '$R' = '3.4' ] || [ '$R' = '3.5' ]; then apt-key adv --keyserver keyserver.ubuntu.com --recv E084DAB9; fi"
  - sudo sh -c "if [ '$R' = '3.4' ]; then add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu trusty/' -y; fi"
  - sudo sh -c "if [ '$R' = '3.5' ]; then add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/' -y; fi"
  - sudo sh -c "if [ '$R' = '3.4' ] || [ '$R' = '3.5' ]; then apt-get update -qq; fi"
  - sudo apt-get install -y --force-yes r-base
  - sudo sh -c "if [ '$R' != '3.5' ]; then apt-get install -y --force-yes r-cran-rserve; fi"
  - sudo sh -c "if [ '$R' = '3.5' ]; then wget \"https://www.rforge.net/Rserve/snapshot/Rserve_1.8-6.tar.gz\"; fi"
  - sudo sh -c "if [ '$R' = '3.5' ]; then R CMD INSTALL Rserve_1.8-6.tar.gz; fi"
  - sudo sh -c "if [ '$LINTR' = '1' ]; then sudo apt-get install --yes r-base-dev; fi"
  - sudo mkdir -p ~/R/Library
  - sudo echo 'R_LIBS=~/R/Library' > ~/.Renviron
  - sudo echo 'options(repos = "https://cran.rstudio.com")' > ~/.Rprofile
  - sudo sh -c "Rscript -e 'if(!\"psy\" %in% rownames(installed.packages())) { install.packages(\"psy\", dependencies = TRUE) }';"
  - sudo sh -c "Rscript -e 'if(!\"gplots\" %in% rownames(installed.packages())) { install.packages(\"gplots\", dependencies = TRUE) }'"
  - sudo sh -c "Rscript -e 'if(!\"ggplot2\" %in% rownames(installed.packages())) { install.packages(\"ggplot2\", dependencies = TRUE) }'"
  - sudo sh -c "if [ '$LINTR' = '1' ]; then Rscript -e 'if(!\"lintr\" %in% rownames(installed.packages())) { install.packages(\"lintr\", dependencies = TRUE) }'; fi"
  - sudo R CMD Rserve
  - sh -c "mysql -e 'CREATE DATABASE qdnatool_test;'"
  - chmod -R 777 ./app/tmp
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require \"satooshi/php-coveralls=v1.0.1\"; fi"
  - sh -c "if [ '$PHPUNIT' != '3.7.33' ]; then composer remove --dev \"phpunit/phpunit\"; fi"
  - composer require "phpunit/phpunit=$PHPUNIT"
  - sh -c "if [ '$PHPCS' = '1' ]; then cd $TRAVIS_BUILD_DIR/app; Vendor/bin/phpcs --config-set installed_paths Vendor/cakephp/cakephp-codesniffer; fi"
  - phpenv rehash
  - echo -e "<?php\nclass DATABASE_CONFIG {\n\n\tpublic \$test = array(\n\t\t'datasource' => 'Database/Mysql',\n\t\t'database' => 'qdnatool_test',\n\t\t'host' => '0.0.0.0',\n\t\t'login' => 'travis',\n\t\t'persistent' => false,\n\t);\n}" > app/Config/database.php
  - echo -e "<?php\n\$config = array(\n\t'Rserve' => array(\n\t\t'host' => 'localhost',\n\t\t'port' => 6311,\n\t\t'debug' => false\n\t)\n);\n" > app/Config/rserve.php

script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then cd $TRAVIS_BUILD_DIR/app; Vendor/bin/cake test app AllTests --stderr --coverage-clover ../build/logs/clover.xml --configuration ../phpunit.xml; fi;"
  - sh -c "if [ '$PHPCS' = '1' ]; then cd $TRAVIS_BUILD_DIR/app; Vendor/bin/phpcs -p --extensions=php --standard=CakePHP --ignore=Plugin --ignore=Vendor --ignore=webroot/js/ckeditor -n $TRAVIS_BUILD_DIR; fi;"
  - sh -c "if [ '$PHPCS' != '1' ] && [ '$COVERALLS' != 1 ] && [ '$LINTR' != 1 ]; then cd $TRAVIS_BUILD_DIR/app; Vendor/bin/cake test app AllTests --stderr; fi"
  - sh -c "if [ '$LINTR' = '1' ]; then cd $TRAVIS_BUILD_DIR; ./bin/travis-linter.sh; fi"
after_success:
  - sh -c "if [ '$COVERALLS' = '1' ]; then cd $TRAVIS_BUILD_DIR; php app/Vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
